name: Build and test
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint dependencies
        run: pnpm lint-shared-versions

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm vitest run

      - name: Build app
        run: pnpm build

      - name: Build API documentation
        run: pnpm build-docs

      # TODO: errors are ignored right now
      - name: Create license report
        run: pnpm build-license-report || true;
